config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root 'products#index'
  resources :products

  resource :cart, only: [ :show ] do
    post :add, path: "add/:id"
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :find_categories

  def initialize_cart
    @cart = Cart.build_from_hash session
  end

  def find_categories
    @categories = Category.all
  end

  def authenticate_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: 'You are not allowed to perform that operation'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_cart.html.haml
-if @cart
  %p.navbar-text.navbar-right
    -if @cart.empty?
      Your cart is empty.
    -else
      =link_to "You have #{pluralize @cart.count, "item"}.", cart_path

app/views/application/_nav.html.erb
<div class='container-fluid'>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"><%= image_tag('logo4-bake&cake-300x150.png')%></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Products', products_path %></li>
          <li class="dropdown nav-item">
            <%= link_to "#", data: { toggle: "dropdown" } do %>
            Categories
            <span class="caret"></span>
            <%- end %>
            <ul class="dropdown-menu">
              <% @categories.each do |category| %>
              <li><%= link_to category.name, category %></li>
              <% end %>
            </ul>
          </li>
        </ul>
        <p class="navbar-text navbar-right">
          <% if user_signed_in? %>
          Logged in as <%= current_user.name %>.
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
          <%= link_to "Login", new_user_session_path, class: "navbar-link" %>
          <% end %>
        </p>
        <%= render 'application/cart' %>
      </div>
    </nav>
  </div>